spring:
  application:
    name: cloudrun-dataclean
gcp:
  project: '${PROJECT_ID}'
  secrets:
    versionId: 1

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true